force-app/main/default/objects/exam__c/exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/exam__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/exam__c/fields/datetime_of_exam__c.field-meta.xml
<CustomField>
    <fullName>datetime_of_exam__c</fullName>
    <label>Datetime of Exam</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/exam__c/fields/total_score__c.field-meta.xml
<CustomField>
    <fullName>total_score__c</fullName>
    <label>Total Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/question__c/fields/exam__c.field-meta.xml
<CustomField>
    <fullName>exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>exam__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/question__c/fields/score__c.field-meta.xml
<CustomField>
    <fullName>score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExamsTableController.cls
public class ExamsTableController {
    
    @AuraEnabled
    public static List<exam__c> getExams(Id contactId) {
        try {
            return [
                    SELECT
                        Name, datetime_of_exam__c, total_score__c,
                        (SELECT Name, score__c FROM questions__r)
                    FROM
                        exam__c
                    WHERE
                        contact__c = :contactId
                    ORDER BY
                        datetime_of_exam__c DESC
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}